name: google_ui
description: Google UI is an open-source UI library for developing cross-platform apps using Flutter with "Material Design 2.0"
version: 2.7.0
homepage: https://github.com/edsulaiman/google_ui
repository: https://github.com/edsulaiman/google_ui

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^0.14.0+3
  intl: ^0.17.0
  spring: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
